### ISSUE TITLE
Spectral Line check boxes do not clear up

### ISSUE THREAD

**Issue by biprateep** [biprateep/prospect#1]
If you accidentally do not select the Quality flag but check one of the spectral feature boxes, and then move to the next spectra, the checkboxes in the absorption column do not automatically clear up

**Comment by armengau** [comment]
I thought it was ok, but not yet... I'm investigating...

**Comment by armengau** [comment]
This one was more tricky.
I'm not 100% sure yet the issue is solved, but my tests seem ok now (ie I see the issue disappear before/after fix).
This is some tricky javascript / bokeh callback stuff...

Same as before I comited the fix in my local branch but could not push to your repo.
The fix is actually one line move! : 

```
+++ b/py/prospect/js/update_plot.js
@@ -87,7 +87,6 @@ if (cb_obj == ispectrumslider) {
             spectral_feature_flag_emission_on.push(i);
         }
     }
-    vi_spectral_feature_input_emission.active = spectral_feature_flag_emission_on;
 
     var spectral_feature_flag_absorption_on = [];
     for (var i=0; i<spectral_features_absorption_slabels.length; i++) {
@@ -95,9 +94,9 @@ if (cb_obj == ispectrumslider) {
             spectral_feature_flag_absorption_on.push(i);
         }
     }
+    vi_spectral_feature_input_emission.active = spectral_feature_flag_emission_on;
     vi_spectral_feature_input_absorption.active = spectral_feature_flag_absorption_on;
 
-
     vi_z_input.value = (metadata.data['VI_z'][i_spectrum]).trim();

```

The reason is that when you write "myradiowidget.active = some_values" then this triggers the call to the related callback, here `self.vi_spectral_feature_callback`. This, with the two widgets emission/absorption on the same data, generates some nasty side effect.

**Comment by armengau** [comment]
Please try this fix, I hope it works for you too!

**Comment by biprateep** [comment]
@armengau Thanks again. This was a simple fix that was hard for me to figure out. I changed the code in this commit https://github.com/biprateep/prospect/commit/c83c74edd6e99b4d936f0bf2843cd456f2f0bc92 . I added you as an author in case we need it in the future.
